Repository gin-contrib/sessions, pull requests merged in 2025-05, with the labels that each got.

#289 Reverting Session() returning nil if session does not exist (issue #287)
  sessions.go
Labels: bug

#282 feat: different stores for many sessions #144
  README.md
  cookie/cookie_test.go
  memcached/memcached_test.go
  memstore/memstore_test.go
  mongo/mongomgo/mongomgo_test.go
  postgres/postgres_test.go
  redis/redis_test.go
  sessions.go
  tester/tester.go
Labels: enhancement

#251 feat: filesystem store backend
  README.md
  _example/filesystem/main.go
  filesystem/filesystem.go
  filesystem/filesystem_test.go
Labels: feature
